name: vivally Demo

on:
  push:
    branches:
main
  pull_request:
    branches:
main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build and Test
        run:  xcodebuild test -project vivally.xcodeproj -scheme CodecovDemo -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.5' build test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
