name: Code Coverage

on:
  push:
    branches:
      - main  # Modify this to match your repository's main branch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: 12.x  # Modify to your Xcode version

      - name: Build and run tests
        run: |
          xcodebuild test -project vivally.xcodeproj -scheme vivally -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.5'
          xcodebuild test -project vivally.xcodeproj -scheme vivally -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.5' -enableCodeCoverage YES

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}